leaf:
  jdbc:
    url: jdbc:mysql://192.168.90.181:3306/leaf?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: stagecs
    password: wjh_stage_mariadb_%$865
  snowflake:
    zk:
      address: 192.168.90.182:2181

#redis配置
---
spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.90.230:7002,192.168.90.230:7003,192.168.90.230:7004

logging:
  file:
    path: /data/servicesLog/logs
